#!/usr/bin/env bash
set -euo pipefail

# ── Generate .env from pass ───────────────────────────────────────────
# Reads secrets from the pass store and writes a .env file.
# Edit the pass paths below to match your store layout.
#
# Usage:
#   ./deploy/gen-env.sh              # strategy .env → stdout
#   ./deploy/gen-env.sh > .env       # write strategy .env
#   ./deploy/gen-env.sh | ssh jc@<IP> "cat > ~/.env"
#
#   ./deploy/gen-env.sh --hermes     # write ~/.hermes/.env directly

if [[ "${1:-}" == "--hermes" ]]; then
  mkdir -p ~/.hermes
  cat > ~/.hermes/.env <<EOF
# ~/.hermes/.env — Jean-Claude AI COO secrets
# Generated by deploy/gen-env.sh --hermes — do not edit by hand

# ── Required ──────────────────────────────────────────────────────────────────
ANTHROPIC_API_KEY=$(pass layer3/ai/console.anthropic.com/jean-claude-key)

# ── Slack ─────────────────────────────────────────────────────────────────────
SLACK_BOT_TOKEN=$(pass layer3/slack.com/yellow/bot_token)
SLACK_APP_TOKEN=$(pass layer3/slack.com/yellow/app_token)
SLACK_HOME_CHANNEL=$(pass layer3/slack.com/yellow/home_channel)
SLACK_ALLOWED_USERS=$(pass layer3/slack.com/yellow/allowed_users)

# ── Telegram ──────────────────────────────────────────────────────────────────
TELEGRAM_BOT_TOKEN=$(pass layer3/telegram.org/jean_claude_yellow_bot/token)
TELEGRAM_HOME_CHANNEL=$(pass layer3/telegram.org/jean_claude_yellow_bot/home_channel)
TELEGRAM_ALLOWED_USERS=$(pass layer3/telegram.org/jean_claude_yellow_bot/allowed_users)

# ── On-chain & market data ────────────────────────────────────────────────────
DUNE_API_KEY=$(pass layer3/dune.com/mod@yellow.org/apikey)
CMC_API_KEY=$(pass layer3/pro.coinmarketcap.com/mod@yellow.org/apikey)

# ── Notion task sync ──────────────────────────────────────────────────────────
NOTION_API_KEY=$(pass layer3/notion.so/mod@yellow.org/apikey)
NOTION_DATABASE_ID=31f75b8f-eb04-80bd-ae9d-000b93bf0dbd

# ── EVM queries (cast) ────────────────────────────────────────────────────────
ETH_RPC_URL=$(pass layer3/yellow/mainnet/infura/rpc_wss_url)

# ── Runtime paths (set by start_gateway.sh — do not override here) ───────────
# MESSAGING_CWD is set automatically by scripts/start_gateway.sh
EOF
  echo "Written to ~/.hermes/.env" >&2
  exit 0
fi

cat <<EOF
SSH_PUBLIC_KEY="$(ssh-add -L | head -1)"
ANTHROPIC_API_KEY=$(pass layer3/ai/console.anthropic.com/jean-claude-key)
DUNE_API_KEY=$(pass layer3/dune.com/mod@yellow.org/apikey)
CMC_API_KEY=$(pass layer3/pro.coinmarketcap.com/mod@yellow.org/apikey)
NOTION_API_KEY=$(pass layer3/notion.so/mod@yellow.org/apikey)
NOTION_DATABASE_ID=31f75b8f-eb04-80bd-ae9d-000b93bf0dbd
SLACK_BOT_TOKEN=$(pass layer3/slack.com/yellow/bot_token)
SLACK_APP_TOKEN=$(pass layer3/slack.com/yellow/app_token)
SLACK_HOME_CHANNEL=$(pass layer3/slack.com/yellow/home_channel)
SLACK_ALLOWED_USERS=$(pass layer3/slack.com/yellow/allowed_users)
TELEGRAM_BOT_TOKEN=$(pass layer3/telegram.org/jean_claude_yellow_bot/token)
TELEGRAM_HOME_CHANNEL=$(pass layer3/telegram.org/jean_claude_yellow_bot/home_channel)
TELEGRAM_ALLOWED_USERS=$(pass layer3/telegram.org/jean_claude_yellow_bot/allowed_users)
ETH_RPC_URL=$(pass layer3/yellow/mainnet/infura/rpc_wss_url)
EOF
